name: dart_commons
version: 1.0.2
author: Jim Simon <jim.j.simon@gmail.com>
description: A collection of utilities for working with the Dart programming language.
homepage: https://github.com/jimsimon/dart_commons
dependencies:
  test: ">=0.12.0 <0.13.0"