name: dart_commons
version: 0.0.0
author: Jim Simon
description: A collection of utilities for working with the Dart programming language.
homepage: https://github.com/jimsimon/dart_commons
dependencies:
  unittest: any
dev_dependencies:
  darter:
    git:
      ref: develop
      url: https://github.com/jimsimon/darter.git

#dependencies:
#  unittest: any