name: dart_commons
version: 1.0.1
author: Jim Simon <jim.j.simon@gmail.com>
description: A collection of utilities for working with the Dart programming language.
homepage: https://github.com/jimsimon/dart_commons
dependencies:
  unittest: ">=0.11.1+1 <0.12.0"